name: Create Staging Builds

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: staging
  build_ios:
    type: build
    params:
      platform: ios
      profile: staging
